[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
cre_ico_solana = "9X5si3xhU4nFVh7FkGaC3n251xoN5JBoys9AEnrfkzxh"

[programs.localnet]
cre_ico_solana = "9X5si3xhU4nFVh7FkGaC3n251xoN5JBoys9AEnrfkzxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "https://proportionate-purple-snow.solana-devnet.quiknode.pro/5697002902222def8695762623210bcca30a6b7b/"
wallet = "/home/letho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
